apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nocobase.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistent.size | default "10Gi" }}
  storageClassName: {{ .Values.persistent.storageClassName | quote }}
